# Generated by Django 5.1.15 on 2026-06-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affordability', '0002_statement_total_outstanding_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='total_outstanding_debt',
        ),
    ]
