# Generated by Django 5.1.15 on 2026-06-14 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affordability', '0003_remove_statement_total_outstanding_debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('user', 'statement_period'), name='unique_user_statement_period'),
        ),
    ]
